### ISSUE TITLE
Cannot flatten Array of strings

### ISSUE THREAD

**Issue by mcastorina** [Lauriat/funct#4]
```python
>>> Array('10', Array('20', '30')).flatten()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$HOME/.local/lib/python3.9/site-packages/funct/Array.py", line 1009, in flatten
    return r.flatten
  File "$HOME/.local/lib/python3.9/site-packages/funct/Array.py", line 1009, in flatten
    return r.flatten
  File "$HOME/.local/lib/python3.9/site-packages/funct/Array.py", line 1009, in flatten
    return r.flatten
  [Previous line repeated 987 more times]
  File "$HOME/.local/lib/python3.9/site-packages/funct/Array.py", line 1007, in flatten
    r = Array(e for s in self for e in (s if isinstance(s, Iterable) else [s]))
  File "$HOME/.local/lib/python3.9/site-packages/funct/Array.py", line 42, in __init__
    args = list(args[0])
  File "$HOME/.local/lib/python3.9/site-packages/funct/Array.py", line 1007, in <genexpr>
    r = Array(e for s in self for e in (s if isinstance(s, Iterable) else [s]))
  File "/usr/lib/python3.9/abc.py", line 98, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
```

Expected: `Array('10', '20', '30')`
Version: `Funct==0.9.2`

**Comment by Lauriat** [comment]
Thanks for the bug report!
